### ISSUE TITLE
Update to angular 13 and publish library in IVY format

### ISSUE THREAD

**Issue by zlajson** [cloudflare/stream-angular#12]
Hello,

as of now, consumers that are having angular version >= 13 are getting NGCC build warning:

Processing legacy "View Engine" libraries:
@cloudflare/stream-angular
Encourage the library authors to publish an Ivy distribution.

Would be nice to see this project updated to angular 13 and release the library with IVY enabled  and compilationMode partial.

**Comment by iliyaeffati** [comment]
Any progress on this issue? I have the same issue with Angular 13.
![Screenshot 2022-02-22 at 12 39 43](https://user-images.githubusercontent.com/7510949/155125086-33fa5696-364f-4d21-a7ef-11d0653801a0.png)

**Comment by third774** [comment]
Hey, y'all! Just wanted to let you know we're taking a look at this and hope to have an update for you soon!

**Comment by third774** [comment]
We've just published a release candidate for this under the `@next` tag. Please give it a go by running `npm i @cloudflare/stream-angular@next` and let me know if you encounter any issues!

**Comment by zlajson** [comment]
I can confirm that using this version 1.0.0-rc.1 fixes this issue.

Thanks!
