### ISSUE TITLE
Use cloudflarestream.com instead of videodelivery.net

### ISSUE THREAD

**Issue by benmarsh** [cloudflare/stream-angular#21]
We're seeing some user reports of video streaming not working in their region - which may be down to the following issue.

<img width="803" alt="Screenshot 2022-05-05 at 09 43 07" src="https://user-images.githubusercontent.com/150741/166892635-35eb4214-ee00-40df-8378-19972f69c956.png">

I was looking for a way to move to the backup domain, but it appears **videodelivery.net** URLs are hardcoded in the plugin.

Could we have an option to either;
- manually switch to use the backup domain, via an @Input attribute
- automatically see if videodelivery.net is not accessible, then use the backup domain
- use a configurable custom base URL, so it can be set using a config variable

**Comment by third774** [comment]
Releasing `v1.0.1` with this change! Thanks!
