### ISSUE TITLE
Include ability to set unique subdomain 

### ISSUE THREAD

**Issue by benmarsh** [cloudflare/stream-angular#25]
Could we have the ability to set the unique customer subdomain on the component so it fetches video from the unique URL as per the announcement on cloudflare.com -
<img width="791" alt="Screenshot 2022-09-05 at 13 42 05" src="https://user-images.githubusercontent.com/150741/188452012-82b42118-3256-4b7b-8baf-e8b08374a3e4.png">

**Comment by irvinebroque** [comment]
See https://github.com/cloudflare/stream-react/issues/73 — we'd welcome a pull request to this repository as well.
