### ISSUE TITLE
Player not working on iOS 

### ISSUE THREAD

**Issue by mattchangegamers** [cloudflare/stream-angular#3]
We are using this player in a hybrid app (cordova) and in the past week or so it stopped working in iOS. The reason it's erroring is because it's calling window.parent.postMessage with the targetOrigin being document.referrer and on iOS hybrid that is "" and that is causing a 'Syntax Error: The string did not match the expected pattern'. 

Here's a post with the same issue  from someone else in the cloudflare forum that no one has replied to either: https://community.cloudflare.com/t/embedded-html-not-working-for-video-in-mobile-app/206140

**Comment by third774** [comment]
@mattchangegamers thank you for reporting! A change has been pushed out that should resolve this. Please let us know if you're running into any other issues!

**Comment by mattchangegamers** [comment]
thank you! it works!
